#!/usr/bin/env python3
"""Report on docs/ coverage and staleness, and generate a plain INDEX.md.

Deliberately standalone: the index it writes is readable by a person, by
Claude, by GitHub, or by any future agent. It does not require, produce for, or
depend on any particular doc-search tooling.

Usage:
    index.py --root <dir> [--docs <dir>] [--emit] [--json]
"""
import argparse, json, os, re, subprocess, sys

CHARS_PER_TOKEN = 3.6
INDEX_NAME = 'INDEX.md'
LARGE_CORPUS = 100        # docs beyond which an always-loaded index stops paying
H1 = re.compile(r'^#\s+(.*\S)\s*$')
HEADING = re.compile(r'^#{1,6}\s')
LINK = re.compile(r'\[([^\]]*)\]\(([^)]+)\)')


def docs_files(docs):
    out = []
    for base, dirs, names in os.walk(docs):
        dirs[:] = [d for d in dirs if not d.startswith('.')]
        for n in sorted(names):
            if n.lower().endswith('.md') and n != INDEX_NAME:
                out.append(os.path.join(base, n))
    return sorted(out)


def describe(path):
    """First H1 as title, first real paragraph as summary."""
    title, summary = os.path.basename(path), ''
    try:
        lines = open(path, encoding='utf-8', errors='replace').read().splitlines()
    except OSError:
        return title, summary, 0
    para = []
    for line in lines:
        m = H1.match(line)
        if m and title == os.path.basename(path):
            title = m.group(1)
            continue
        if HEADING.match(line):
            if para:
                break
            continue
        if line.strip():
            para.append(line.strip())
        elif para:
            break
    summary = ' '.join(para)
    if len(summary) > 200:
        summary = summary[:197].rsplit(' ', 1)[0] + '…'
    try:
        size = os.path.getsize(path)
    except OSError:
        size = 0
    return title, summary, size


def existing_index(docs):
    p = os.path.join(docs, INDEX_NAME)
    if not os.path.isfile(p):
        return None, []
    try:
        text = open(p, encoding='utf-8', errors='replace').read()
    except OSError:
        return p, []
    return p, [(t, target) for t, target in LINK.findall(text)]


def referenced(root, docs, files):
    """Which docs are mentioned anywhere outside docs/ itself."""
    hits = {}
    for f in files:
        name = os.path.basename(f)
        try:
            r = subprocess.run(['git', '-C', root, 'grep', '-l', '--', name],
                               capture_output=True, text=True, timeout=20)
            found = [l for l in r.stdout.splitlines()
                     if l.strip() and not l.startswith(os.path.relpath(docs, root))]
        except Exception:
            found = []
        hits[f] = found
    return hits


def tok(n):
    return round(n / CHARS_PER_TOKEN)


def render(docs, entries):
    out = ['# Documentation index', '',
           'Generated by the `doc-index` skill. One line per document.', '']
    by_dir = {}
    for path, title, summary, size in entries:
        d = os.path.relpath(os.path.dirname(path), docs)
        by_dir.setdefault(d, []).append((path, title, summary, size))
    for d in sorted(by_dir):
        if d != '.':
            out.append('## %s' % d)
            out.append('')
        for path, title, summary, size in by_dir[d]:
            rel = os.path.relpath(path, docs)
            out.append('- [%s](%s) — %s' % (title, rel, summary or '_no summary_'))
        out.append('')
    return '\n'.join(out).rstrip() + '\n'


def report(root, docs, entries, idx_path, idx_links, refs, emit):
    print('DOC INDEX — %s\n' % os.path.relpath(docs, root))
    total = sum(e[3] for e in entries)
    print('CORPUS')
    print('  documents            %d' % len(entries))
    print('  total size           %s B  (~%s tokens)' % (f'{total:,}', f'{tok(total):,}'))
    print('  index                %s' % (os.path.relpath(idx_path, root) if idx_path else 'absent'))

    print('\nDOCUMENTS')
    for path, title, summary, size in entries:
        print('  %-34s %7s B  ~%5s t  %s' % (os.path.relpath(path, docs)[:34],
                                             f'{size:,}', f'{tok(size):,}',
                                             'unsummarised' if not summary else ''))

    print('\nFINDINGS')
    out = []
    listed = set()
    for _title, target in idx_links:
        t = target.split('#')[0]
        if not t or t.startswith(('http://', 'https://')):
            continue
        full = os.path.normpath(os.path.join(docs, t))
        listed.add(full)
        if not os.path.isfile(full):
            out.append('  [class 1] index points at a missing file: %s' % t)
    if idx_path:
        for path, _t, _s, _z in entries:
            if os.path.normpath(path) not in listed:
                out.append('  [class 1] document not in the index: %s'
                           % os.path.relpath(path, docs))
    else:
        out.append('  [class 1] no %s — nothing lists what documentation exists' % INDEX_NAME)
    for path, _t, summary, _z in entries:
        if not summary:
            out.append('  [class 2] no summary paragraph: %s' % os.path.relpath(path, docs))
    for path, where in refs.items():
        if not where:
            out.append('  [class 3] referenced nowhere outside docs/: %s'
                       % os.path.relpath(path, docs))
    if len(entries) > LARGE_CORPUS:
        out.append('  [class 3] %d documents — an always-loaded index stops paying '
                   'around %d; see the corpus scaling note in CLAUDE-TODO.md'
                   % (len(entries), LARGE_CORPUS))
    print('\n'.join(out) if out else '  none')

    if emit:
        print('\n--- proposed %s ---' % INDEX_NAME)
        print(render(docs, entries))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', required=True)
    ap.add_argument('--docs')
    ap.add_argument('--emit', action='store_true',
                    help='print the proposed INDEX.md; it is never written by this script')
    ap.add_argument('--json', action='store_true')
    args = ap.parse_args()
    root = os.path.realpath(args.root)
    docs = os.path.realpath(args.docs) if args.docs else os.path.join(root, 'docs')
    if not os.path.isdir(docs):
        sys.exit('no docs directory at %s' % docs)

    files = docs_files(docs)
    entries = [(f,) + describe(f) for f in files]
    idx_path, idx_links = existing_index(docs)
    refs = referenced(root, docs, files)
    if args.json:
        print(json.dumps(dict(root=root, docs=docs,
                              entries=[dict(path=p, title=t, summary=s, bytes=z)
                                       for p, t, s, z in entries],
                              index=idx_path, index_links=idx_links,
                              referenced={k: v for k, v in refs.items()},
                              proposed=render(docs, entries)), indent=2))
    else:
        report(root, docs, entries, idx_path, idx_links, refs, args.emit)


if __name__ == '__main__':
    main()
